spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: 192.168.89.200
    port: 5672
    username: guest
    password: guest
    virtual-host: '/'
  output:
    ansi:
      enabled: always
  boot:
    admin:
      url: http://localhost:${server.port}/admin
logging:
  level:
    root: info
debug: false
server:
  port: 8979



#spring.jackson.serialization.indent_output=true
#endpoints.health.sensitive=false



